name: cocktails
description: Cocktail app
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: '>=3.1.3 <4.0.0'

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter

  # Hive
  hive: ^2.2.3
  hive_flutter:

  json_annotation: ^4.8.1
  json_serializable: ^6.7.1
  http: ^1.1.0
  lottie: ^2.7.0
  go_router: ^12.1.1
  get: ^4.6.1
  collection: ^1.17.2
  cached_network_image: ^3.3.0
  shimmer: ^3.0.0
  share_plus: ^6.3.4

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.6
  animated_splash_screen: ^1.3.0
  appinio_swiper: ^2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Hive
  hive_generator:
  build_runner:

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^3.0.1
  test: ^1.24.3

  flutter_launcher_icons: ^0.13.1

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  assets:
    - assets/lottie/cocktail_loading.json
    - assets/lottie/icon_settings_regular.json
    - assets/lottie/icon_settings_solid.json
    - assets/lottie/icon_favorite_regular.json
    - assets/lottie/icon_favorite_solid.json
    - assets/lottie/icon_home_regular.json
    - assets/lottie/icon_home_solid.json
    - assets/lottie/icon_swipe_regular.json
    - assets/lottie/icon_swipe_solid.json
    - assets/img/cocktail.png
    - assets/img/beer.png
    - assets/img/cocoa.png
    - assets/img/coffee-cup.png
    - assets/img/frappe.png
    - assets/img/liqueur.png
    - assets/img/open-box.png
    - assets/img/punch.png
    - assets/img/soda.png
    - assets/img/soft-drinks.png
    - assets/img/tequila-shot.png
    - assets/img/no-wifi.png
    - assets/img/bar-counter.png
    - assets/img/beverage.png
    - assets/img/drink.png
    - assets/img/grocery.png
    - assets/img/letter.png
    - assets/img/drunk.png
    - assets/img/sort-asc.png
    - assets/img/sort-desc.png
    - assets/img/glass/balloon.png
    - assets/img/glass/beer.png
    - assets/img/glass/brandy.png
    - assets/img/glass/champagne.png
    - assets/img/glass/cocktail.png
    - assets/img/glass/coffee-cup.png
    - assets/img/glass/collins.png
    - assets/img/glass/copper-mug.png
    - assets/img/glass/cordial.png
    - assets/img/glass/coupe.png
    - assets/img/glass/highball.png
    - assets/img/glass/hurricane.png
    - assets/img/glass/irish-coffee.png
    - assets/img/glass/jar.png
    - assets/img/glass/margarita.png
    - assets/img/glass/martini.png
    - assets/img/glass/old-fashioned.png
    - assets/img/glass/parfait.png
    - assets/img/glass/pilsner.png
    - assets/img/glass/pint.png
    - assets/img/glass/pitcher.png
    - assets/img/glass/smoothie.png
    - assets/img/glass/tequila-shot.png
    - assets/img/glass/whiskey.png
    - assets/img/glass/whiskey-sour.png
    - assets/img/glass/white-wine.png
    - assets/img/glass/wine-glass.png

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Karla
      fonts:
        - asset: fonts/Karla-Regular.ttf
          weight: 400
        - asset: fonts/Karla-Medium.ttf
          weight: 500
        - asset: fonts/Karla-SemiBold.ttf
          weight: 600
        - asset: fonts/Karla-Bold.ttf
          weight: 700
        - asset: fonts/Karla-Italic.ttf
          style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages

#flutter_launcher_icons:
#  android: true
#  ios: true
#  image_path: "assets/icon/icon.png"
#  min_sdk_android: 21 # android min sdk min:16, default 21
#  remove_alpha_ios: true
#  background_color: "#ffffff"
#  web:
#    generate: true
#    image_path: "assets/icon/icon.png"
#    background_color: "#hexcode"
#    theme_color: "#hexcode"
#  windows:
#    generate: true
#    image_path: "assets/icon/icon.png"
#    icon_size: 48 # min:48, max:256, default: 48
#  macos:
#    generate: true
#    image_path: "assets/icon/icon.png"